on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  unit-test:
    uses: ./.github/workflows/coverage.yml
  canary:
    uses: ./.github/workflows/canary.yml
